### PR TITLE
Adapted to Ardour 6.9.0, new VPO location

### PR DESCRIPTION
**Pull request by robertaramar**
I have re-loaded all .sfz-files from a new location at `~/opt/Virtual Playing Orchestra3`. I just think that putting stuff under `/opt` as a _**regular user**_ is not wanted by some users.
I would appreciate if you would accept my PR

### CODE REVIEW

**Comment by robertaramar** [comment]
If you want to create a release based on this, let me know what it will be, I can then change the download instructions accordingly.

**Comment by michaelwillis** [comment]
@robertaramar Thanks! I'll take a look at this.

**Comment by michaelwillis** [comment]
@robertaramar I noticed what looks like several symbolic links to `../../../../../opt/Virtual-Playing-Orchestra3`... Is that intentional? The relative path won't necessarily work on different systems.

I keep wishing that I could find a better, singular way of allowing people to pick a directory where Virtual Playing Orchestra can be found, some kind of prompt when using the template to set up a new Ardour session. I'm going to ask the Ardour devs for suggestions.

**Comment by robertaramar** [comment]
I do get your point. However, in this particular case, the location of the template is fixed:
`~/.config/ardour6/templates/Virtual Playing Orchestra 2022`
Therefore, the relative symlinks point exactly to
`~/opt/Virtual Playing Orchestra3`
But I do agree, it would be better to have the user pick the location of VPO.
I did a .lua-script to import the 16 tracks of our band rehearsals. We might use such method to create the template. That would allow users to pick file locations.
Can we somehow "chat"? Telegram? Signal? Threema? IRC? Just no WhatsApp ;-)

**Comment by michaelwillis** [comment]
@robertaramar Thanks for your work on this. The symlinks won't work on MacOS, because the relative path to the home dir is different, but I didn't want to leave you hanging for too long. If I really want to support both operating systems, I should probably have two separate releases of the template.

**Comment by TauPan** [comment]
I stumbled over this because <del>the README still tells users to put the orchestra files into /opt</del> apparently I've overlooked the new instructions.

Also what about https://github.com/michaelwillis/virtual-playing-orchestra-ardour-template/pull/6 ? It seems it would be more useful for users with non-standard setups. (For example I put my music experiments into my nextcloud folder in ~/Nextcloud/Music/Taupan/ardour and this requires me to put the orchestra files into ~/Nextcloud/opt. Even then I'm still being hit by #5 so I have to reconfigure the sfizz plugins manually. The symlinks in the externals folder do point to the correct files.)

I see the following settings in the template file:
~~~xml
<lv2 last-preset-uri="" last-preset-label="" parameter-changed-since-last-preset="1" template-dir="/home/rschneid/.config/ardour6/templates/Virtual Playing Orchestra 2022" state-dir="state1">
~~~

I'm guessing that this may be causing the issues, since `/home/rschneid` does not exist on my machine?

**Pull request merged**
